version: "3.8"

services:

  #################################
  # Bidding: The Bidding microservice
  #################################
  bidding:
    image: hullojalapenos/bidding:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root:root@localhost:3306/bidding
  #################################
  # Job: The Jobs microservice
  #################################
  job:
    image: hullojalapenos/job:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/jobs
  #################################
  # calljob: The test_invoke_http.py program
  #################################
  calljob:
    image: hullojalapenos/calljob:1.0
    restart: always
    environment:
      jobURL: http://jobs:5001/jobs
  # #################################
  # # Notification: The Notification microservice
  # #################################
  # notification:
  #   image: jiayii01/notification:1.0
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/notification
  # #################################
  # # accept_freelancer: The accept freelancer complex microservice
  # #################################
  # accept_freelancer:
  #   image: jiayii01/accept_freelancer:1.0
  #   restart: always
  #   environment:
  #       dbURL: mysql+mysqlconnector://root:root@host.docker.internal:3306/accept_freelancer



