version: "3.8"

services:

  #################################
  # Bidding: The Bidding microservice
  #################################
  bidding:
    image: hullojalapenos/bidding:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/bidding
  #################################
  # Job: The Job microservice
  #################################
  job:
    image: hullojalapenos/job:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/job
  #################################
  # notification: The notification microservice
  #################################
  # notification:
  #   image: hullojalapenos/notification:1.0
  #   restart: always
  #   environment:
  #     dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/notification
  #################################
  # accept_freelancer: The accept freelancer complex microservice
  #################################
  # accept_freelancer:
  #   image: hullojalapenos/accept_freelancer:1.0
  #   restart: always
  #   environment:
  #       dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/accept_freelancer



