version: "3.8"

volumes:
  rabbitmq_data: 

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
  #################################
  # Bidding: The Bidding microservice
  #################################
  bidding:
    build:
      context: bidding/
      dockerfile: Dockerfile
    image: jiayii01/bidding:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/bidding
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"
  #################################
  # Freelancer: The Freelancer microservice
  #################################
  freelancer:
    build:
      context: freelancers/
      dockerfile: Dockerfile
    image: hullojalapenos/freelancers:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/freelancers
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"
  #################################
  # Job: The Jobs microservice
  #################################
  jobs:
    build:
        context: jobs/
        dockerfile: Dockerfile
    image: hullojalapenos/job:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/jobs
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
  # #################################
  # # Notification: The Notification microservice
  # #################################
  notification:
    build:
        context: notification/
        dockerfile: Dockerfile
    image: hullojalapenos/notification:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/notification
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"
  # #################################
  # # accept_freelancer: The accept freelancer complex microservice
  # #################################
  accept_freelancer:
    build:
        context: accept_freelancer/
        dockerfile: Dockerfile
    image: hullojalapenos/accept_freelancer:1.0
    restart: always
    depends_on:
      - jobs
      - bidding
      - rabbitmq
      - notification
      
    environment:
        rabbit_host: rabbitmq
        rabbit_port: 5672
        jobs_URL: http://jobs:5001/jobs
        bidding_URL: http://bidding:5002/bidding
        notification_URL: http://notification:5003/notification
        PYTHONUNBUFFERED: 1
    ports:
    - "5100:5100"



